@startuml

' Hides the 'c' that appears next to classes
hide circle

skinparam DefaultFontName "Monospaced"
skinparam DefaultFontSize "10"
skinparam MinClassWidth 140

'_______________________________________________________________________
' Colors
'_______________________________________________________________________
' Apply background color: Use  $color_var_name  (colors defined w/ #)
' Apply outline    color: Use #$color_var_name  (colors defined w/ #)
'
' e.g. class ClassName #$outline_color $bg_color
'
!$color_0= "#00afd7"
!$color_1= "#af5fd7"
!$color_2= "#000000"

!$def_bg_= "#ffffff"

skinparam ClassBackgroundColor  $def_bg_
skinparam ClassBorderColor      $color_0
skinparam NoteBackgroundColor   $def_bg_
skinparam NoteBorderColor       $color_1
skinparam ArrowThickness        2
skinparam ClassBorderThickness  2

'_______________________________________________________________________
' Global params
'_______________________________________________________________________


'_______________________________________________________________________
' Legend
'_______________________________________________________________________
' --|> Inheritance, child on top  e.g. ChildClass  --|> ParentClass
' <|-- Inheritance, parent on top e.g. ParentClass --|> ChildClass
' *--  Composition
' o--  Aggregation
' --   Association
' -->  Directed Association
' ..>  Dependency
' <|.. Realization
'_______________________________________________________________________

class QnxDriver
class ClockWrapper
class MomentarySwitch
{
  -int on_value_
  -int reading_

  -int settle_time_in_ms_
  -int long_hold_time_in_ms_
  -int short_hold_time_in_ms_
  -int mult_input_time_gap_

  -int sw_state_
  -int prev_state_

  -int prev_debounced_input_
  -int multi_input_count_

  -unsigned long prev_ms_
  -unsigned long on_time_ms_
  -unsigned long release_time_ms_
  -unsigned long time_since_off_

  -SwitchState sw_state_type_

  +InputType get_input_type()
  +int       debounce_input()
  +int       get_pin()
  +int       get_reading()
  +bool      is_short_press()
}

class Adafruit_AlphaNum4
class TimeCtrl
{
  -ClockWrapper clock_
  -LedDisplay  *display_
  +bool         is_on_fri()
}
class UserCtrl
{
  -LedDisplay* display_
}
class FluxAlarm
{
  -uint8_t day
  -uint8_t hr
  -uint8_t min
}


class LedDisplay
{
  -Adafruit_AlphaNum4 led_segments_
  +void write_disp_str    (const char*)
  +void write_disp_str_num(const char* str, uint8_t num)
  +void write_disp_hr_min (uint8_t hr     , uint8_t min)
  +void write_disp_time   (uint8_t        , uint8_t)
}

class AudioCtrl

hide  QnxDriver           members
hide  ClockWrapper        members
hide  Adafruit_AlphaNum4  members
hide  AudioCtrl           members

QnxDriver     *-down- UserCtrl
QnxDriver     *-down- TimeCtrl
QnxDriver     *-down- LedDisplay
TimeCtrl      *-up-   LedDisplay
UserCtrl      *-up-   LedDisplay
TimeCtrl      *-      ClockWrapper
TimeCtrl      *-down- FluxAlarm

UserCtrl      *-down- MomentarySwitch
FluxAlarm     -      AudioCtrl

LedDisplay     *- Adafruit_AlphaNum4

json "Class Description" as class_desc {
  "TopLevel          " : "Top level functionality."
, "TimeCalcs         " : "Static time constants and calculations."
, "ClockWrapper      " : "Clock object and time setter functions based on hardware implementation. Tracks off Friday week."
, "MomentarySwitch   " : "State logic for buttons."
, "FluxAlarm         " : "Alarm information."
, "Adafruit_AlphaNum4" : "Third party class to control LED display."
, "UserCtrl"           : "Interaction between user inputs and time set."
, "LedDisplay       " : ""
}

@enduml