@startuml

''



'_______________________________________________________________________
' Global params
'_______________________________________________________________________


'_______________________________________________________________________
' Legend
'_______________________________________________________________________
' --|> Inheritance, child on top  e.g. ChildClass  --|> ParentClass
' <|-- Inheritance, parent on top e.g. ParentClass --|> ChildClass
' --   Association, need to communicate, no strong relationship
' -->  Directed Association, classA knows of classB, but not vice versa
' *--  Composition
' o--  Aggregation
' ..>  Dependency
' <|.. Realization
'_______________________________________________________________________

class QnxDriver
class ClockWrapper
class Adafruit_AlphaNum4
class TimeCtrl
class UserCtrl
class FluxAlarm
class AlphaDisplay
class AudioCtrl
class MomentarySwitch

QnxDriver     *-down- UserCtrl
QnxDriver     *-down- TimeCtrl
QnxDriver     *-down- AlphaDisplay
TimeCtrl      o-up-   AlphaDisplay
UserCtrl      o-up-   AlphaDisplay
TimeCtrl      *-down- ClockWrapper
TimeCtrl      *-down- FluxAlarm
ClockWrapper  *-      DS3231
note "QnxDriver mediates data flow \nfrom UserCtrl to TimeCtrl" as Note0
UserCtrl      ..      Note0
TimeCtrl      ..      Note0

UserCtrl      *-down- MomentarySwitch
FluxAlarm     -       AudioCtrl

AlphaDisplay   *- Adafruit_AlphaNum4

'_______________________________________________________________________
' Class descriptions
json "Class Description" as class_desc {
  "TopLevel           " : "Top level functionality."
, "TimeCalcs          " : "Static time constants and calculations."
, "ClockWrapper       " : "Clock object and time setter functions based on hardware implementation. Tracks off Friday week."
, "MomentarySwitch    " : "State logic for buttons."
, "FluxAlarm          " : "Alarm information."
, "Adafruit_AlphaNum4 " : "Third party class to control LED display."
, "UserCtrl           " : "Interaction between user inputs and time set."
, "AlphaDisplay       " : "Alphanumeric display control and formatting."
, "QNXDriver          " : "QNX driver class."
}
@enduml
