@startuml nine-eighty-alarm-base-uml

'_______________________________________________________________________
' Global params
'_______________________________________________________________________


'_______________________________________________________________________
' Legend
'_______________________________________________________________________
' --|> Inheritance, child on top  e.g. ChildClass  --|> ParentClass
' <|-- Inheritance, parent on top e.g. ParentClass --|> ChildClass
' --   Association, need to communicate, no strong relationship
' -->  Directed Association, classA knows of classB, but not vice versa
' *--  Composition
' o--  Aggregation
' ..>  Dependency
' <|.. Realization
'_______________________________________________________________________

class QnxDriver
class ClockWrapper
class Adafruit_AlphaNum4
class TimeCtrl
class UserCtrl
class Alarm
class AlphaDisplay
class AudioCtrl
class MomentarySwitch

QnxDriver     *-down- UserCtrl
QnxDriver     *-down- TimeCtrl
QnxDriver     *-down- AlphaDisplay
UserCtrl      o-up-   AlphaDisplay
TimeCtrl      *-down- ClockWrapper
TimeCtrl      *-down- "1..*" Alarm
ClockWrapper  *-down- DS3231
Alarm         *-down- AudioCtrl

note "QnxDriver mediates data flow \nfrom UserCtrl to TimeCtrl" as Note0
UserCtrl      ..     Note0
TimeCtrl      ..     Note0

UserCtrl      *-down- "1..*" MomentarySwitch
UserCtrl      *-down- "1..*" LatchingSwitch

AlphaDisplay   *- Adafruit_AlphaNum4

@enduml
