@startuml style-nine-eighty

'_______________________________________________________________________
' Colors
'_______________________________________________________________________
' Apply background color: Use  $color_var_name  (colors defined w/ #)
' Apply outline    color: Use #$color_var_name  (colors defined w/ #)
'
' e.g. class ClassName #$outline_color $bg_color
'_______________________________________________________________________

!$font_size_norm = "14"

' Hides the 'c' that appears next to classes
hide circle

skinparam ClassBackgroundColor  $bg_def_
skinparam ClassBorderThickness  2
skinparam ClassBorderColor      $color_0

skinparam Class {
  ArrowColor      $fg_mute
}

skinparam ArrowThickness        1

skinparam DefaultFontColor      $fg_def_
skinparam DefaultFontName       "Monospaced"
skinparam DefaultFontSize       $font_size_norm

skinparam MinClassWidth         200
'skinparam backgroundcolor       transparent

<style>
note {
  BackgroundColor $bg_def_
  LineColor       $color_1
  FontSize        $font_size_norm
}
</style>

' Ortho spec breaks the smaller files
skinparam Linetype              ortho

@enduml